---
name: Evergine Sample
version: dev
slug: evergine_sample
description: Sample add-on that add-on that hosts a WASM WebGL wiewer made with Evergine
url: https://github.com/vicfergar/addon-evergine_sample
ingress: true
ingress_stream: true
panel_icon: mdi:floor-plan
init: false
homeassistant: 0.92.0b2
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  80/tcp: null
ports_description:
  80/tcp: Web interface (Not required for Ingress)
hassio_api: true
hassio_role: homeassistant
homeassistant_api: true
auth_api: true
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
